services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_DB: book_network_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - book-network
    restart: unless-stopped

  bsn-api:
    container_name: bsn-api
    build:
      context: ./book-network
      dockerfile: ../docker/backend/Dockerfile
    environment:
        SPRING_PROFILES_ACTIVE: dev

    ports:
      - 8088:8088
    networks:
      - book-network
    depends_on:
        - postgres

  bsn-ui:
    container_name: bsn-ui
    build:
      context: ./book-network-ui
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - 8080:80
    networks:
      - book-network
    depends_on:
        - bsn-api

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    volumes:
      - ./imports/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    networks:
      - book-network
    command:
      - "start-dev"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm-export.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
networks:
  book-network:
    driver: bridge

volumes:
  postgres:
    driver: local