services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_DB: book_network_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - book-network
    restart: unless-stopped

  bsn-api:
    container_name: bsn-api
    image: f3th1/bsn-api:latest
    environment:
      EMAIL_HOST_NAME: ${EMAIL_HOST_NAME}
      EMAIL_USER_NAME: ${EMAIL_USER_NAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - 8088:8088
    networks:
      - book-network
    depends_on:
        - postgres

  bsn-ui:
    container_name: bsn-ui
    image: f3th1/bsn-ui:latest
    ports:
      - 8080:80
    networks:
      - book-network
    depends_on:
        - bsn-api
networks:
  book-network:
    driver: bridge

volumes:
  postgres:
    driver: local