
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_network_api
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
    database: postgresql
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    contexts: dev, faker
    enabled: true
  mail:
    host: ${EMAIL_HOST_NAME}
    port: 465
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: true
    protocol: smtp
  thymeleaf:
    cache: false
    prefix: classpath:/templates/mail/
    suffix: .html
  output:
    ansi:
      enabled: always

application:
  picsur:
    url: https://picsur.fethi.synology.me
    access-key: ERxVhFENrAMr2Ue3OY0DymIMlqSLKCYo
  security:
    cors:
      origins: http://localhost:4200, http://localhost:8080,http://192.168.1.155:8080, http://192.168.1.155:8088
      max-age: 3600
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration-time: 86400000 # 1 day
      refresh-token:
        expiration-time: 2592000000 # 30 days
  mailing:
    front-end:
      activation-url: http://localhost:4200/activate-account
  role:
    default: ROLE_USER
  front:
    url: http://localhost:5173

logging:
  level:
    liquibase: INFO
    com.benseddik.book: DEBUG
    org.springframework.cloud.openfeign: ERROR
server:
  port: 8088
